version: '3'

services:
  nacos-0:
    image: registry-dev.uihcloud.cn/com.uih.uplus.base/nacos:dev-20220607-20041
    labels:
      - com.host.description=nacos-0
    container_name: nacos-0
    command: /bin/bash -c "cd /root/nacos/target/ && java -jar -Dnacos.preferHostnameOverIp=true nacos-server.jar --spring.config.location=bootstrap.yml"
    ports:
      - 30102:8848
      - 31102:9848
    volumes:
      - ./bootstrap.yml:/root/nacos/target/bootstrap.yml
      - ./cluster.conf:/root/nacos/conf/cluster.conf

  nacos-1:
    image: registry-dev.uihcloud.cn/com.uih.uplus.base/nacos:dev-20220607-20041
    labels:
      - com.host.description=nacos-1
    container_name: nacos-1
    command: /bin/bash -c "cd /root/nacos/target/ && java -jar -Dnacos.preferHostnameOverIp=true nacos-server.jar --spring.config.location=bootstrap.yml"
    ports:
      - 30112:8848
      - 31112:9848
    volumes:
      - ./bootstrap.yml:/root/nacos/target/bootstrap.yml
      - ./cluster.conf:/root/nacos/conf/cluster.conf

  nacos-2:
    image: registry-dev.uihcloud.cn/com.uih.uplus.base/nacos:dev-20220607-20041
    labels:
      - com.host.description=nacos-2
    container_name: nacos-2
    command: /bin/bash -c "cd /root/nacos/target/ && java -jar -Dnacos.preferHostnameOverIp=true nacos-server.jar --spring.config.location=bootstrap.yml"
    ports:
      - 30122:8848
      - 31122:9848
    volumes:
      - ./bootstrap.yml:/root/nacos/target/bootstrap.yml
      - ./cluster.conf:/root/nacos/conf/cluster.conf